HC = ghc

CFLAGS = -O2 -I/usr/include/blike
LIBS = `pkg-config blike --libs`

TEST000A_PROG = hs_test000a
TEST000A_SRCS = blike.hs hs_bl_wrapper.c $(TEST000A_PROG).hs

TEST001A_PROG = hs_test001a
TEST001A_SRCS = blike.hs hs_bl_wrapper.c $(TEST001A_PROG).hs

TEST002A_PROG = hs_test002a
TEST002A_SRCS = blike.hs hs_bl_wrapper.c $(TEST002A_PROG).hs

TEST003A_PROG = hs_test003a
TEST003A_SRCS = blike.hs hs_bl_wrapper.c $(TEST003A_PROG).hs

TEST004A_PROG = hs_test004a
TEST004A_SRCS = blike.hs hs_bl_wrapper.c $(TEST004A_PROG).hs

TEST005A_PROG = hs_test005a
TEST005A_SRCS = blike.hs hs_bl_wrapper.c $(TEST005A_PROG).hs

TEST006A_PROG = hs_test006a
TEST006A_SRCS = blike.hs hs_bl_wrapper.c $(TEST006A_PROG).hs

TEST008A_PROG = hs_test008a
TEST008A_SRCS = blike.hs hs_bl_wrapper.c $(TEST008A_PROG).hs

TEST010A_PROG = hs_test010a
TEST010A_SRCS = blike.hs hs_bl_wrapper.c $(TEST010A_PROG).hs

TEST011A_PROG = hs_test011a
TEST011A_SRCS = blike.hs hs_bl_wrapper.c $(TEST011A_PROG).hs

TEST012A_PROG = hs_test012a
TEST012A_SRCS = blike.hs hs_bl_wrapper.c $(TEST012A_PROG).hs

TEST015A_PROG = hs_test015a
TEST015A_SRCS = blike.hs hs_bl_wrapper.c $(TEST015A_PROG).hs

TEST015B_PROG = hs_test015b
TEST015B_SRCS = blike.hs hs_bl_wrapper.c $(TEST015B_PROG).hs

TEST016A_PROG = hs_test016a
TEST016A_SRCS = blike.hs hs_bl_wrapper.c $(TEST016A_PROG).hs

TEST017A_PROG = hs_test017a
TEST017A_SRCS = blike.hs hs_bl_wrapper.c $(TEST017A_PROG).hs

TEST018A_PROG = hs_test018a
TEST018A_SRCS = blike.hs hs_bl_wrapper.c $(TEST018A_PROG).hs

TEST020A_PROG = hs_test020a
TEST020A_SRCS = blike.hs hs_bl_wrapper.c $(TEST020A_PROG).hs

TEST021A_PROG = hs_test021a
TEST021A_SRCS = blike.hs hs_bl_wrapper.c $(TEST021A_PROG).hs

BBALL00A_PROG = hs_bball00a
BBALL00A_SRCS = blike.hs hs_bl_wrapper.c $(BBALL00A_PROG).hs

BOXES00A_PROG = hs_boxes00a
BOXES00A_SRCS = blike.hs hs_bl_wrapper.c $(BOXES00A_PROG).hs

MSGK00A_PROG = hs_msgk00a
MSGK00A_SRCS = blike.hs hs_bl_wrapper.c $(MSGK00A_PROG).hs

MSGK01A_PROG = hs_msgk01a
MSGK01A_SRCS = blike.hs hs_bl_wrapper.c $(MSGK01A_PROG).hs

MT_XOR0A_PROG = hs_mt_xor0a
MT_XOR0A_SRCS = blike.hs hs_bl_wrapper.c $(MT_XOR0A_PROG).hs

KCUBE00A_PROG = hs_kcube00a
KCUBE00A_SRCS = blike.hs hs_bl_wrapper.c $(KCUBE00A_PROG).hs

all: $(TEST000A_PROG) $(TEST001A_PROG) $(TEST000A_PROG) $(TEST001A_PROG) $(TEST002A_PROG) $(TEST003A_PROG) $(TEST004A_PROG) $(TEST005A_PROG) $(TEST006A_PROG) $(TEST008A_PROG) $(TEST010A_PROG) $(TEST011A_PROG) $(TEST012A_PROG) $(TEST015A_PROG) $(TEST015B_PROG) $(TEST016A_PROG) $(TEST017A_PROG) $(TEST018A_PROG) $(TEST020A_PROG) $(TEST021A_PROG) $(BBALL00A_PROG) $(BOXES00A_PROG) $(MSGK00A_PROG) $(MSGK01A_PROG) $(MT_XOR0A_PROG) $(KCUBE00A_PROG)

$(TEST000A_PROG): $(TEST000A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST000A_SRCS) $(LIBS) -o $@

$(TEST001A_PROG): $(TEST001A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST001A_SRCS) $(LIBS) -o $@

$(TEST002A_PROG): $(TEST002A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST002A_SRCS) $(LIBS) -o $@

$(TEST003A_PROG): $(TEST003A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST003A_SRCS) $(LIBS) -o $@

$(TEST004A_PROG): $(TEST004A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST004A_SRCS) $(LIBS) -o $@

$(TEST005A_PROG): $(TEST005A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST005A_SRCS) $(LIBS) -o $@

$(TEST006A_PROG): $(TEST006A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST006A_SRCS) $(LIBS) -o $@

$(TEST008A_PROG): $(TEST008A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST008A_SRCS) $(LIBS) -o $@

$(TEST010A_PROG): $(TEST010A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST010A_SRCS) $(LIBS) -o $@

$(TEST011A_PROG): $(TEST011A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST011A_SRCS) $(LIBS) -o $@

$(TEST012A_PROG): $(TEST012A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST012A_SRCS) $(LIBS) -o $@

$(TEST015A_PROG): $(TEST015A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST015A_SRCS) $(LIBS) -o $@

$(TEST015B_PROG): $(TEST015B_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST015B_SRCS) $(LIBS) -o $@

$(TEST016A_PROG): $(TEST016A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST016A_SRCS) $(LIBS) -o $@

$(TEST017A_PROG): $(TEST017A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST017A_SRCS) $(LIBS) -o $@

$(TEST018A_PROG): $(TEST018A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST018A_SRCS) $(LIBS) -o $@

$(TEST020A_PROG): $(TEST020A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST020A_SRCS) $(LIBS) -o $@

$(TEST021A_PROG): $(TEST021A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(TEST021A_SRCS) $(LIBS) -o $@

$(BBALL00A_PROG): $(BBALL00A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(BBALL00A_SRCS) $(LIBS) -o $@

$(BOXES00A_PROG): $(BOXES00A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(BOXES00A_SRCS) $(LIBS) -o $@

$(MSGK00A_PROG): $(MSGK00A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(MSGK00A_SRCS) $(LIBS) -o $@

$(MSGK01A_PROG): $(MSGK01A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(MSGK01A_SRCS) $(LIBS) -o $@

$(MT_XOR0A_PROG): $(MT_XOR0A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(MT_XOR0A_SRCS) $(LIBS) -o $@

$(KCUBE00A_PROG): $(KCUBE00A_SRCS)
	$(HC) --make -no-hs-main $(CFLAGS) $(KCUBE00A_SRCS) $(LIBS) -o $@

clean:
	rm -f *.o *.hi *_stub.h
	rm -f $(TEST000A_PROG)
	rm -f $(TEST001A_PROG)
	rm -f $(TEST002A_PROG)
	rm -f $(TEST003A_PROG)
	rm -f $(TEST004A_PROG)
	rm -f $(TEST005A_PROG)
	rm -f $(TEST006A_PROG)
	rm -f $(TEST008A_PROG)
	rm -f $(TEST010A_PROG)
	rm -f $(TEST011A_PROG)
	rm -f $(TEST012A_PROG)
	rm -f $(TEST015A_PROG)
	rm -f $(TEST015B_PROG)
	rm -f $(TEST016A_PROG)
	rm -f $(TEST017A_PROG)
	rm -f $(TEST018A_PROG)
	rm -f $(TEST020A_PROG)
	rm -f $(TEST021A_PROG)
	rm -f $(BBALL00A_PROG)
	rm -f $(BOXES00A_PROG)
	rm -f $(MSGK00A_PROG)
	rm -f $(MSGK01A_PROG)
	rm -f $(MT_XOR0A_PROG)
	rm -f $(KCUBE00A_PROG)

install:
	echo ""

uninstall:
	echo ""

